MODEL:
  META_ARCHITECTURE: "fcn8s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '/home/panqiao/dhu719/ZYJ/VOC2012'


TEST:
  WEIGHT: '/home/panqiao/dhu719/ZYJ/checkpoints/train_fcn8s_atonce/fcn8s.pth'

OUTPUT_DIR: "/home/panqiao/dhu719/ZYJ/checkpoints/inference_fcn8s_atonce"

