
MODEL:
  META_ARCHITECTURE: "fcn8s"

  BACKBONE:
    PRETRAINED: True
    WEIGHT: '/home/panqiao/dhu719/ZYJ/model_zoo/vgg16-397923af.pth'

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '/home/panqiao/dhu719/ZYJ/VOC2012'

SOLVER:
  MAX_EPOCHS: 13
  CHECKPOINT_PERIOD: 13

OUTPUT_DIR: "/home/panqiao/dhu719/ZYJ/checkpoints/train_fcn8s_atonce"
